#136 filter function
Cykelinspektionen/MjukvaruProjekt pull request #164
Opened 2018-12-07 14:42 UTC by jakobemilandersson

#### What does this PR do?
Integrates the filter-function on the client with the back-end and makes the filter look more like the decided design.
(Please tell me if something should be changed with the current design!)
[Issue](LINK_TO_ISSUE)
#136 
##### Why are we doing this? Any context or related work?
To make it possible for the user to filter through all the bike ads.
#### Where should a reviewer start?
Filter.js
#### Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
closes #136

2018-12-07 18:28 UTC, FredSoderberg requested changes
Nice addition, just check one of the comments about missing fields.... and ESlint next time :P

2018-12-07 18:28 UTC, FredSoderberg commented on Bikeini/components/Filter.js
>            <ItemCheckbox title={rowData[0].title} category={rowData[0].category} id={rowData[0].id} isChecked={rowData[0].isChecked} onChange={this.updateCheckBoxes} />
Why is there 3 empty "places"?

2018-12-07 18:28 UTC, FredSoderberg commented on Bikeini/components/Filter.js
> +        >
really Nice addition... but on iPhone XS and galaxy 6 its really yanky. Still better then nothing but I would guess there is a better package for this *host host*  👍

2018-12-07 18:29 UTC, FredSoderberg commented on Bikeini/components/Filter.js
>            <ItemCheckbox title={rowData[0].title} category={rowData[0].category} id={rowData[0].id} isChecked={rowData[0].isChecked} onChange={this.updateCheckBoxes} />
![image](https://user-images.githubusercontent.com/14044644/49665830-6ac18900-fa56-11e8-887f-e64e606e2062.png)

2018-12-07 18:46 UTC, FredSoderberg commented on Bikeini/components/Filter.js
> +        >
Its a neat feature which needs to be included in more places 👍

2018-12-08 11:37 UTC, jakobemilandersson commented on Bikeini/components/Filter.js
>            <ItemCheckbox title={rowData[0].title} category={rowData[0].category} id={rowData[0].id} isChecked={rowData[0].isChecked} onChange={this.updateCheckBoxes} />
To make it look like the design on Marvel! -> Seperating the two different "groups" of options. I can merge them togheter into one group instead. 😄

2018-12-08 11:39 UTC, jakobemilandersson commented on Bikeini/components/Filter.js
> +        >
Yeah sadly it doesn't really work as it should on Android devices when running through Expo so it looks kind of weird... 😞 Will be looking for a better option but can remove it for this PR if it's too wonky!

2018-12-08 11:47 UTC, FredSoderberg commented on Bikeini/components/Filter.js
>            <ItemCheckbox title={rowData[0].title} category={rowData[0].category} id={rowData[0].id} isChecked={rowData[0].isChecked} onChange={this.updateCheckBoxes} />
Ahhh sorry, misses That in the design!

2018-12-08 11:49 UTC, FredSoderberg commented on Bikeini/components/Filter.js
> +        >
No let’s keep it, it fulfills it’s purpose almost ;) so it’s better than the alternative, we can write it up as an enhancement.

2018-12-08 11:50 UTC, FredSoderberg approved these changes
Really nice!

2018-12-08 11:50 UTC, merged